site_name: DSGE

repo_url: https://github.com/FRBNY-DSGE/DSGE.jl.git

nav:
    - Home: index.md
    - Model Design: model_design.md
    - Running An Existing Model: running_existing_model.md
    - Advanced Usage: advanced_usage.md
    - Input Data: input_data.md
    - FRBNY Model Input Data: frbny_data.md
    - Implementation Details: implementation_details.md
    - Solving the Model: solving.md
    - Estimation: estimation.md
    - Forecasting: forecast.md
    - Computing Means and Bands: means_bands.md
    - Alternative Policies: altpolicy.md
    - Alternative Scenarios: scenarios.md
    - Plotting: plotting.md
    - Algorithms: algorithms.md
    - Contributing: contributing.md
    - MATLAB to Julia Transition, Estimation: MatlabtoJuliTransition.md
    - MATLAB to Julia Transition, Forecast: julia_forecasting.md
    - License: license.md