mkdocs.yml
docs/
    index.md
    model_desgin.md
    running_existing_model.md
    advanced_usage.md
    input_data.md
    frbny_data.md
    implementation_details.md
    solving.md
    estimation.md
    forecast.md
    means_bands.md
    altpolicy.md
    scenarios.md
    plotting.md
    algorithms.md
    contributing.md
    MatlabtoJuliTransition.md
    julia_forecasting.md
    license.md